### ISSUE TITLE
Proxy not respected during a restart (but resolves after a save of the profile)

### ISSUE THREAD

**Issue by srizzling** [JetBrains/teamcity-amazon-ecs-plugin#16]
Hi there,

When we do a restart of TeamCity, the plugin shows the following stacktrace (suggesting it cannot connect to the metadata endpoint)

<details><summary>stacktrace suggesting can't connect to metadata endpoint</summary>
Failed to initialize cloud client 'awsecs'.Unable to execute HTTP request: Connect to ecs.ap-southeast-2.amazonaws.com:443 [ecs.ap-southeast-2.amazonaws.com/54.240.195.89] failed: connect timed out
Hide stacktrace
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to ecs.ap-southeast-2.amazonaws.com:443 [ecs.ap-southeast-2.amazonaws.com/54.240.195.89] failed: connect timed out
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1114)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1064)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
at com.amazonaws.services.ecs.AmazonECSClient.doInvoke(AmazonECSClient.java:2675)
at com.amazonaws.services.ecs.AmazonECSClient.invoke(AmazonECSClient.java:2651)
at com.amazonaws.services.ecs.AmazonECSClient.executeListTasks(AmazonECSClient.java:1703)
at com.amazonaws.services.ecs.AmazonECSClient.listTasks(AmazonECSClient.java:1679)
at jetbrains.buildServer.clouds.ecs.apiConnector.EcsApiConnectorImpl.listTasks(EcsApiConnectorImpl.kt:146)
at jetbrains.buildServer.clouds.ecs.apiConnector.EcsApiConnectorImpl.listRunningTasks(EcsApiConnectorImpl.kt:128)
at jetbrains.buildServer.clouds.ecs.EcsCloudImageImpl.populateInstances(EcsCloudImageImpl.kt:82)
at jetbrains.buildServer.clouds.ecs.EcsCloudClientFactory.createNewClient(EcsCloudClientFactory.kt:63)
at jetbrains.buildServer.clouds.server.impl.ProjectCloudManagerImpl.createNewClient(ProjectCloudManagerImpl.java:386)
at jetbrains.buildServer.clouds.server.impl.ProjectCloudManagerImpl.getClient(ProjectCloudManagerImpl.java:305)
at jetbrains.buildServer.clouds.server.impl.CloudManagerBaseImpl.getClient(CloudManagerBaseImpl.java:408)
at jetbrains.buildServer.clouds.server.impl.CloudInstancesProviderImpl.iterateProfileInstances(CloudInstancesProviderImpl.java:77)
at jetbrains.buildServer.clouds.server.impl.CloudInstancesProviderImpl.iterateInstances(CloudInstancesProviderImpl.java:67)
at jetbrains.buildServer.clouds.server.impl.instances.RunningInstanceTrackerImpl.update(RunningInstanceTrackerImpl.java:98)
at jetbrains.buildServer.clouds.server.impl.instances.RunningInstanceTrackerImpl$1.serverStartup(RunningInstanceTrackerImpl.java:70)
at sun.reflect.GeneratedMethodAccessor203.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at jetbrains.buildServer.util.EventDispatcher$3.run(EventDispatcher.java:126)
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:71)
at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:120)
at jetbrains.buildServer.serverSide.ServerSideEventDispatcher.superDispatch(ServerSideEventDispatcher.java:13)
at jetbrains.buildServer.serverSide.ServerSideEventDispatcher$1.run(ServerSideEventDispatcher.java:2)
at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAs(SecurityContextImpl.java:48)
at jetbrains.buildServer.serverSide.impl.auth.SecurityContextImpl.runAsSystem(SecurityContextImpl.java:49)
at jetbrains.buildServer.serverSide.ServerSideEventDispatcher.dispatch(ServerSideEventDispatcher.java:12)
at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:70)
at com.sun.proxy.$Proxy22.serverStartup(Unknown Source)
at jetbrains.buildServer.serverSide.impl.BuildServerLifecycleProcessor.doStartup(BuildServerLifecycleProcessor.java:16)
at jetbrains.buildServer.maintenance.TeamCityDispatcherServlet$WebApplicationCreatorAndDestroyer.createApplication(TeamCityDispatcherServlet.java:30)
at jetbrains.buildServer.maintenance.StartupProcessor.doApplicationStarting(StartupProcessor.java:252)
at jetbrains.buildServer.maintenance.StartupProcessor.access$700(StartupProcessor.java:537)
at jetbrains.buildServer.maintenance.StartupProcessor$3.call(StartupProcessor.java:4)
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:86)
at jetbrains.buildServer.maintenance.StartupProcessor.processConcreteStage(StartupProcessor.java:242)
at jetbrains.buildServer.maintenance.StartupProcessor.processConcreteStageSafe(StartupProcessor.java:57)
at jetbrains.buildServer.maintenance.StartupProcessor.processTeamCityLifecycle(StartupProcessor.java:246)
at jetbrains.buildServer.maintenance.StartupProcessor.access$000(StartupProcessor.java:31)
at jetbrains.buildServer.maintenance.StartupProcessor$1.run(StartupProcessor.java:3)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to ecs.ap-southeast-2.amazonaws.com:443 [ecs.ap-southeast-2.amazonaws.com/54.240.195.89] failed: connect timed out
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:150)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
at com.amazonaws.http.conn.$Proxy329.connect(Unknown Source)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1236)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
... 46 more
Caused by: java.net.SocketTimeoutException: connect timed out
at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:132)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
... 62 more 
</details>

But once we get into the CloudProfile and hit save the error goes away. This is probably because we need to configure a proxy for our outgoing connections. And perhaps on a teamcity restart the plugin doesn't check the property values. (i.e related PR: #13)

I wouldn't know the correct place where it would need to be placed, but perhaps the retreival of the proxy vars need to be done when the plugin intializes during a teamcity server start.

**Comment by ekoshkin** [comment]
Hi, @srizzling 
i've added debug logging in d3c2c6e0fa6b8954bf320d0a5f039c451e442d7a
Please try (this build)[https://teamcity.jetbrains.com/viewLog.html?buildId=1361451&buildTypeId=TestDrive_TeamCityAmazonEcsPlugin_Build20172x&tab=artifacts] with debug-all logging preset enabled.

**Comment by srizzling** [comment]
Interestingly the log line is populated here:

```
[2018-03-23 11:57:17,179]  DEBUG [18-03-23 11:56)] - iConnector.EcsApiConnectorImpl - ECS client proxy settings: proxy - proxy.<company>.com, port - 8080, user -  
```

**Comment by ekoshkin** [comment]
so even when error occured after server restart you see valid proxy settings in logs?

**Comment by srizzling** [comment]
Yeah, which is interesting. I'll try and take a network capture and see if its going through the proxy. Other than that, I'm not sure what else this could be.

**Comment by ekoshkin** [comment]
ok, looking forward for new info from you
